384119 Set up queries frontend
DEFRA/ffc-sfd-queries pull request #1
Opened 2024-05-28 11:06 UTC by rtasalem

https://dev.azure.com/defragovuk/DEFRA-FFC/_workitems/edit/384119

2024-05-28 14:34 UTC, rtasalem commented
After building & starting the container, both endpoints (`locahost:3017/queries/healthy` & `localhost:3017/queries/healthz`) are returning `ok` response as expected.

2024-05-28 14:42 UTC, johnwatson484 commented on Dockerfile
> -ARG PORT_DEBUG=9229
Should be using LTS Node version 20.

2024-05-28 14:43 UTC, johnwatson484 commented on docker-compose.yaml
> +      AHWP_HOST: ${AHWP_HOST:-http://localhost:3010}
Don't think this service needs to know anything about the AHWP stub service?

2024-05-28 14:43 UTC, johnwatson484 commented on package.json
> +    "ffc-auth": "^0.12.0",
Need to drop the `^` in this file

2024-05-28 14:44 UTC, johnwatson484 commented on package.json
> +    "ffc-auth": "^0.12.0",
You can update your default npm config to not set them by default

2024-05-28 14:45 UTC, johnwatson484 requested changes
Needs a tweak to the export on `server.js` as `createServer` needs wrapping in `{ }`

Currently app fails to start up

2024-05-28 15:17 UTC, rtasalem commented on Dockerfile
> -ARG PORT_DEBUG=9229
Updated the version to v20.

2024-05-28 15:18 UTC, rtasalem commented on docker-compose.yaml
> +      AHWP_HOST: ${AHWP_HOST:-http://localhost:3010}
Ah thank you, have removed this reference.

2024-05-28 15:18 UTC, rtasalem commented on package.json
> +    "ffc-auth": "^0.12.0",
Done.

2024-05-28 15:40 UTC, johnwatson484 approved these changes

2024-05-29 07:48 UTC, rtasalem commented on package.json
> +    "ffc-auth": "^0.12.0",
> You can update your default npm config to not set them by default

I thought I had but realised I used the wrong command. Have now updated my NPM config so the caret (`^`) is no longer there when I install packages.

2024-05-29 07:49 UTC, merged